- hosts: all
  become: yes
  tasks:
   - name: Install packages to allow apt to use a repository over HTTPS
     apt:
       pkg:
        - apt-transport-https
        - ca-certificates
        - software-properties-common
       state: present
       update_cache: true

   - name: Add Docker’s official GPG key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   - name: Add Docker's APT repository
     apt_repository:
       repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
       state: present

   - name: Install containerd
     apt:
       name: containerd.io
       state: present
       update_cache: true

   - name: Create /etc/containerd directory if it does not exist
     become: yes
     become_user: root
     file:
       path: /etc/containerd
       state: directory
       mode: '0755'

   - name: Configure containerd
     shell: containerd config default > /etc/containerd/config.toml

   - name: Restart containerd
     shell: systemctl restart containerd

   - name: Switch to using 'systemd' cgroup driver
     replace:
       path: /etc/containerd/config.toml
       after: '(\s+)\[plugins\.cri\]'
       regexp : '    systemd_cgroup \= false'
       replace: '    systemd_cgroup = true'
       before: '(\s+)\[plugins\.cri\.containerd\]'
       backup: yes

   - name: Restart containerd
     shell: systemctl restart containerd
