- hosts: all
  become: yes
  tasks:
   - name: Install packages to allow apt to use a repository over HTTPS
     apt:
       name: apt-transport-https
       state: present
       update_cache: true

   - name: Add Kubernetes’s official GPG key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: Add Kubernetes's APT repository
     apt_repository:
       repo: "deb https://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release }} main"
       state: present
       filename: 'kubernetes'

   - name: Install kubelet
     apt:
       name: kubelet=1.18.6-00
       state: present
       update_cache: true

   - name: install kubeadm
     apt:
       name: kubeadm=1.18.6-00
       state: present

   - name: install kubectl
     apt:
       name: kubectl=1.18.6-00
       state: present
       force: yes

   - name: Exclude all Kubernetes packages from any system upgrades
     shell: apt-mark hold kubelet kubeadm kubectl

   - name: Configure cgroup driver used by kubelet on control-plane node
     copy:
       dest: /var/lib/kubelet/config.yaml
       content:  |
         apiVersion: kubelet.config.k8s.io/v1beta1
         kind: KubeletConfiguration
         cgroupDriver: systemd
       owner: root
       group: root
       mode: '0644'

   - name: Reload configuration
     shell: systemctl daemon-reload

   - name: Restart kubelet
     shell: systemctl restart kubelet
