- hosts: all
  become: yes
  tasks:
    - name: "create the {{username}} user"
      user: name="{{username}}" append=yes state=present createhome=yes shell=/bin/bash

    - name: "allow {{username}} to have passwordless sudo"
      lineinfile:
        path: /etc/sudoers
        line: '{{username}} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: "set up authorized keys for the {{username}} user"
      authorized_key: user="{{username}}" key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub